### PR TITLE
Wording suggestions

### PR DESCRIPTION
**Pull request by jfinkhaeuser**
Leave open for now... I'm collecting some suggestions as I read through the doc.

### CODE REVIEW

**Comment by jfinkhaeuser** [comment]
Alright, that's my take on this version.

On the storage and distribution section, I have a few more conceptual suggestions, but they will take me a little longer to write this down. They diverge a little from what's described, but not so substantially as to render these sections entirely wrong. I'm inclined to open a second PR for that, and consider this one here ready for review :)

**Comment by jfinkhaeuser** [comment]
@bedeho

**Comment by bedeho** [comment]
@jens Im trying to merge your fixes, just going through now.

You introduce an authority key, but in this model we are dealing with static objects which are authenticated using some fixed hash. As you seein scheme for `Data Object`, the CID is meant to authetnicate actual data.

Now we can of course separate out a unique identifier from the actual authetnication hash, so for example each object is identified by a unqiue integer for example, and then you store the hash based authetnication value separately, but both would still be part of the  `Data  Object` schema, and it would not be a public key.

**Comment by jens** [comment]
Sorry, wrong Jens. :-)

**Comment by jfinkhaeuser** [comment]
Ok, added the PDF and updated the README, @bedeho

**Pull request merged**
